version: '3.8'

services:
  lisa-website:
    build: .
    container_name: lisa_website_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
